### ISSUE TITLE
difference number samples

### ISSUE THREAD

**Issue by PhoenixAlx** [njvack/bioread#18] opened 2016-02-10 14:53 UTC
Hi

I have a little problem with the file 4Channel.acq (attach two files 4Channel.acq and 4Channel.txt)

In the file 4Channel.txt I can see that th four channels have 4612 datas and whe I do

```
print (data);
print (len(data.channels[0].data));
print (len(data.channels[1].data));
print (len(data.channels[2].data));
print (len(data.channels[3].data));
```
The output is

```
Biopac file (rev 42): 4 channels, 200.0 samples/sec
4612
4611
4610
4609
```

Also I have seen that the datas 4611 and 4612 in channel 0 collected by bioread are distinct to the datas the original file acq.

What does it happen?

Thank for you job

[acq.zip](https://github.com/njvack/bioread/files/124926/acq.zip)

**Comment by njvack** [comment] 2016-02-10 14:58
There's a bug in reading the last few samples of data (it's a long story). I'm working on it and should have it fixed in a week or two.

**Comment by njvack** [comment] 2016-02-10 14:59
Also, this is a dupe of #3

**Closed by njvack** 2016-02-10 14:59 UTC

**Comment by njvack** [comment] 2016-03-24 22:04
Well, it was more than a week or two, but this is fixed in master and once I've cleaned things up and added some tests, it'll get pushed to an actual 1.0 release.
